baseURL = "https://flannon.github.io/"
languageCode = "en-us"
title = "Minimal"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "Flannon Jackson"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "flannon"
    accent = "cyan"
    showBorder = true
    backgroundColor = "white"
    #font = "Raleway" # should match the name on Google Fonts!
    font = "Montserrat" 
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:flannon@5eight5.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/flannon/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/flannon/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/flannon/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/3447107/flannon/"
    name = "stack-overflow"
    weight = 5
